ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "coverImage" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "address" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "emergencyContact" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "gender" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "dob" TIMESTAMP(3);
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "bio" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "preferredTravelStyle" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "favoriteDestinations" TEXT[] DEFAULT ARRAY[]::TEXT[];
