ALTER TABLE "Review" ADD COLUMN IF NOT EXISTS "visitDate" TIMESTAMP(3);
UPDATE "Review" SET "visitDate" = "createdAt" WHERE "visitDate" IS NULL;
ALTER TABLE "Review" ALTER COLUMN "visitDate" SET NOT NULL;
ALTER TABLE "Review" ADD COLUMN IF NOT EXISTS "helpfulCount" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Review" ADD COLUMN IF NOT EXISTS "ownerReply" TEXT;
