export const toSafeUser = (user) => ({
  id: user.id,
  name: user.fullName,
  email: user.email,
  role: user.role,
  avatar: user.profileImage,
  coverImage: user.coverImage,
  phone: user.phone,
  address: user.address,
  emergencyContact: user.emergencyContact,
  gender: user.gender,
  dob: user.dob,
  bio: user.bio,
  preferredTravelStyle: user.preferredTravelStyle,
  favoriteDestinations: user.favoriteDestinations || [],
  createdAt: user.createdAt,
  updatedAt: user.updatedAt,
});
